apiVersion: apps/v1
kind: Deployment
metadata:
  name: coloc-app-deployment
  labels:
    app: coloc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coloc-app
  template:
    metadata:
      labels:
        app: coloc-app
    spec:
      containers:
        - name: coloc-app-server
          image: laamirikhadija/coloc-app:latest
          ports:
            - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: coloc-app-service
spec:
  selector:
    app: coloc-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31110